name: Build and Test

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  test-typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        working-directory: ./ts
        run: npm install
      - name: Build
        working-directory: ./ts
        run: npm run build
      - name: Run tests
        working-directory: ./ts
        run: npm test

  test-javascript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        working-directory: ./js
        run: npm install
      - name: Run tests
        working-directory: ./js
        run: npm test

  test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
#      - name: Install dependencies
#        working-directory: ./py
#        run: pip install -e .
      - name: Run tests
        working-directory: ./py
        run: python -m unittest discover -s tests

  test-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
      - name: Run tests
        working-directory: ./go
        run: go test -v ./...

  test-ruby:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
      - name: Install dependencies
        working-directory: ./rb
        run: |
          gem install bundler
          bundle install
      - name: Run tests
        working-directory: ./rb
        run: ruby test_voxgig_struct.rb

  test-php:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Install dependencies
        working-directory: ./php
        run: composer install
      - name: Run tests
        working-directory: ./php
        run: vendor/bin/phpunit

  test-lua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.4"
      - name: Setup LuaRocks
        uses: leafo/gh-actions-luarocks@v4
      - name: Setup environment
        working-directory: ./lua
        run: |
          chmod +x setup.sh
          ./setup.sh
      - name: Run tests
        working-directory: ./lua
        run: make test
